version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/terraform-cisco-modules/terraform-intersight-pools-resource/actions/workflows/terratest.yml/badge.svg)](https://github.com/terraform-cisco-modules/terraform-intersight-pools-resource/actions/workflows/terratest.yml)
  # Terraform Intersight Pools - Resource
  Manages Intersight Resource Pools
  
  Location in GUI:
  `Pools` » `Create Pool` » `Resource`
  
  ## Easy IMM

  [*Easy IMM - Comprehensive Example*](https://github.com/terraform-cisco-modules/easy-imm-comprehensive-example) - A comprehensive example for policies, pools, and profiles.

  ## Example

  ### main.tf
  ```hcl
  {{ include "examples/complete/main.tf" }}
  ```

  ### provider.tf
  ```hcl
  {{ include "examples/complete/provider.tf" }}
  ```

  ### variables.tf
  ```hcl
  {{ include "examples/complete/variables.tf" }}
  ```

  ## Environment Variables

  ### Terraform Cloud/Enterprise - Workspace Variables
  - Add variable apikey with value of [your-api-key]
  - Add variable secretkey with value of [your-secret-file-content]

  ### Linux
  ```bash
  export TF_VAR_apikey="<your-api-key>"
  export TF_VAR_secretkey=`cat <secret-key-file-location>`
  ```

  ### Windows
  ```bash
  $env:TF_VAR_apikey="<your-api-key>"
  $env:TF_VAR_secretkey="<secret-key-file-location>"
  ```


  {{ .Requirements }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Resources }}
output:
  file: README.md
  mode: replace

sort:
  enabled: false